name: GitHub README Stats Update

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write # Add explicit permissions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate GitHub Stats Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          EXCLUDE_LANGUAGES: "" # Optional: add languages to exclude
          UTC_OFFSET: 1 # Optional: adjust to your timezone

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Update github-profile-summary-cards" || exit 0

      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: main
