name: GitHub README Stats Update

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          USERNAME: victoryotzev
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: true

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Update GitHub stats" || exit 0

      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: main
